interface ProvinceAndMunicipalityOption {
  name: string;
  places?: string[];
}

const provinceAndMunicipality: ProvinceAndMunicipalityOption[] = [
  { name: "Select a Province" },
  {
    name: "Agusan del Norte (incl. City of Butuan)",
    places: [
      "Select a City/Municipality",
      "Buenavista",
      "Butuan",
      "Cabadbaran",
      "Carmen",
      "Jabonga",
      "Kitcharao",
      "Las Nieves",
      "Magallanes",
      "Nasipit",
      "Remedios T. Romualdez",
      "Santiago",
      "Tubay",
    ],
  },
  {
    name: "Agusan del Sur",
    places: [
      "Select a City/Municipality",
      "Bayugan",
      "Bunawan",
      "Esperanza",
      "La Paz",
      "Loreto",
      "Prosperidad",
      "Rosario",
      "San Francisco",
      "San Luis",
      "Santa Josefa",
      "Sibagat",
      "Talacogon",
      "Trento",
      "Veruela",
    ],
  },
  {
    name: "Basilan",
    places: [
      "Select a City/Municipality",
      "Akbar",
      "Al-Barka",
      "Hadji Mohammad Ajul",
      "Hadji Muhtamad",
      "Lamitan",
      "Lantawan",
      "Maluso",
      "Sumisip",
      "Tabuan-Lasa",
      "Tipo-Tipo",
      "Tuburan",
      "Ungkaya Pukan",
    ],
  },
  {
    name: "Bukidnon",
    places: [
      "Select a City/Municipality",
      "Baungon",
      "Cabanglasan",
      "Damulog",
      "Dangcagan",
      "Don Carlos",
      "Impasug-ong",
      "Kadingilan",
      "Kalilangan",
      "Kibawe",
      "Kitaotao",
      "Lantapan",
      "Libona",
      "Malaybalay",
      "Malitbog",
      "Manolo Fortich",
      "Maramag",
      "Pangantucan",
      "Quezon",
      "San Fernando",
      "Sumilao",
      "Talakag",
      "Valencia",
    ],
  },

  {
    name: "Cotabato (North Cotabato)",
    places: [
      "Select a City/Municipality",
      "Alamada",
      "Aleosan",
      "Antipas",
      "Arakan",
      "Banisilan",
      "Carmen",
      "Kabacan",
      "Kidapawan",
      "Libungan",
      "Magpet",
      "Makilala",
      "Matalam",
      "Midsayap",
      "M'lang",
      "Pigkawayan (Pigcawayan)",
      "Pikit",
      "President Roxas",
      "Tulunan",
    ],
  },
  {
    name: "Davao del Norte",
    places: [
      "Select a City/Municipality",
      "Asuncion (Saug)",
      "Braulio E. Dujali",
      "Carmen",
      "Kapalong",
      "New Corella",
      "Panabo",
      "Samal (Island Garden City of Samal)",
      "San Isidro",
      "Santo Tomas",
      "Tagum",
      "Talaingod",
    ],
  },
  {
    name: "Davao del Sur",
    places: [
      "Select a City/Municipality",
      "Bansalan",
      "Davao",
      "Digos",
      "Hagonoy",
      "Kiblawan",
      "Magsaysay",
      "Malalag",
      "Matanao",
      "Padada",
      "Santa Cruz",
      "Sulop",
    ],
  },
  {
    name: "Davao de Oro",
    places: [
      "Select a City/Municipality",
      "Compostela",
      "Laak (San Vicente)",
      "Mabini (Doña Alicia)",
      "Maco",
      "Maragusan (San Mariano)",
      "Mawab",
      "Monkayo",
      "Montevista",
      "Nabunturan",
      "New Bataan",
      "Pantukan",
    ],
  },
  {
    name: "Davao Occidental",
    places: [
      "Select a City/Municipality",
      "Don Marcelino",
      "Jose Abad Santos (Trinidad)",
      "Malita",
      "Santa Maria",
      "Sarangani",
    ],
  },
  {
    name: "Davao Oriental",
    places: [
      "Select a City/Municipality",
      "Baganga",
      "Banaybanay",
      "Boston",
      "Caraga",
      "Cateel",
      "Governor Generoso",
      "Lupon",
      "Manay",
      "Mati",
      "San Isidro",
      "Tarragona",
    ],
  },
  {
    name: "Dinagat Islands",
    places: [
      "Select a City/Municipality",
      "Basilisa (Rizal)",
      "Cagdianao",
      "Dinagat",
      "Libjo (Albor)",
      "Loreto",
      "San Jose",
      "Tubajon",
    ],
  },
  {
    name: "Interim Province",
    places: [
      "Select a City/Municipality",
      "Carmen Cluster",
      "Kabacan Cluster",
      "Midsayap Cluster I",
      "Midsayap Cluster II",
      "Pigcawayan Cluster",
      "Pikit Cluster I",
      "Pikit Cluster II",
      "Pikit Cluster III",
    ],
  },
  {
    name: "Lanao del Norte",
    places: [
      "Select a City/Municipality",
      "Bacolod",
      "Baloi (Balo-i)",
      "Baroy",
      "Iligan",
      "Kapatagan",
      "Kauswagan",
      "Kolambugan",
      "Lala",
      "Linamon",
      "Magsaysay",
      "Maigo",
      "Matungao",
      "Munai",
      "Nunungan",
      "Pantao Ragat",
      "Pantar",
      "Poona Piagapo",
      "Salvador",
      "Sapad",
      "Sultan Naga Dimaporo (Karomatan)",
      "Tagoloan",
      "Tangcal",
      "Tubod",
    ],
  },
  {
    name: "Lanao del Sur",
    places: [
      "Select a City/Municipality",
      "Amai Manabilang (Bumbaran)",
      "Bacolod-Kalawi (Bacolod Grande)",
      "Balabagan",
      "Balindong (Watu)",
      "Bayang",
      "Binidayan",
      "Buadiposo-Buntong",
      "Bubong",
      "Butig",
      "Calanogas",
      "Ditsaan-Ramain",
      "Ganassi",
      "Kapai",
      "Kapatagan",
      "Lumba-Bayabao (Maguing)",
      "Lumbaca-Unayan",
      "Lumbatan",
      "Lumbayanague",
      "Madalum",
      "Madamba",
      "Maguing",
      "Malabang",
      "Marantao",
      "Marawi",
      "Marogong",
      "Masiu",
      "Mulondo",
      "Pagayawan (Tatarikan)",
      "Piagapo",
      "Picong (Sultan Gumander)",
      "Poona Bayabao (Gata)",
      "Pualas",
      "Saguiaran",
      "Sultan Dumalondong",
      "Tagoloan II",
      "Tamparan",
      "Taraka",
      "Tubaran",
      "Tugaya",
      "Wao",
    ],
  },
  {
    name: "Maguindanao del Norte",
    places: [
      "Select a City/Municipality",
      "Barira",
      "Buldon",
      "Cotabato",
      "Datu Blah T. Sinsuat",
      "Datu Odin Sinsuat (Dinaig)",
      "Kabuntalan (Tumbao)",
      "Matanog",
      "Northern Kabuntalan",
      "Parang",
      "Sultan Kudarat (Nuling)",
      "Sultan Mastura",
      "Talitay (Sultan Sumagka)",
      "Upi",
    ],
  },
  {
    name: "Maguindanao del Sur",
    places: [
      "Select a City/Municipality",
      "Ampatuan",
      "Buluan",
      "Datu Abdullah Sangki",
      "Datu Anggal Midtimbang",
      "Datu Hoffer Ampatuan (← Shariff Aguak)",
      "Datu Paglas",
      "Datu Piang",
      "Datu Salibo (← Datu Piang)",
      "Datu Saudi-Ampatuan",
      "Datu Unsay",
      "General Salipada K. Pendatun",
      "Guindulungan",
      "Mamasapano",
      "Mangudadatu",
      "Pagagawan (Datu Montawal)",
      "Pagalungan",
      "Paglat",
      "Pandag",
      "Rajah Buayan",
      "Shariff Aguak (Maganoy)",
      "Shariff Saydona Mustapha",
      "South Upi",
      "Sultan sa Barongis (Lambayong)",
      "Talayan",
    ],
  },
  {
    name: "Misamis Occidental",
    places: [
      "Select a City/Municipality",
      "Aloran",
      "Baliangao",
      "Bonifacio",
      "Calamba",
      "Clarin",
      "Concepcion",
      "Don Victoriano Chiongbian (Don Mariano Marcos)",
      "Jimenez",
      "Lopez Jaena",
      "Oroquieta",
      "Ozamis (Ozamiz)",
      "Panaon",
      "Plaridel",
      "Sapang Dalaga",
      "Sinacaban",
      "Tangub",
      "Tudela",
    ],
  },
  {
    name: "Misamis Oriental",
    places: [
      "Select a City/Municipality",
      "Alubijid",
      "Balingasag",
      "Balingoan",
      "Binuangan",
      "Cagayan de Oro",
      "Claveria",
      "El Salvador",
      "Gingoog",
      "Gitagum",
      "Initao",
      "Jasaan",
      "Kinoguitan",
      "Lagonglong",
      "Laguindingan",
      "Libertad",
      "Lugait",
      "Magsaysay (Linugos)",
      "Manticao",
      "Medina",
      "Naawan",
      "Opol",
      "Salay",
      "Sugbongcogon",
      "Tagoloan",
      "Talisayan",
      "Villanueva",
    ],
  },
  {
    name: "Sarangani",
    places: [
      "Select a City/Municipality",
      "Alabel",
      "Glan",
      "Kiamba",
      "Maasim",
      "Maitum",
      "Malapatan",
      "Malungon",
    ],
  },
  {
    name: "South Cotabato",
    places: [
      "Select a City/Municipality",
      "Banga",
      "General Santos (Dadiangas)",
      "Koronadal",
      "Lake Sebu",
      "Norala",
      "Polomolok",
      "Santo Niño",
      "Surallah",
      "Tampakan",
      "Tantangan",
      "T'Boli",
      "Tupi",
    ],
  },
  {
    name: "Sultan Kudarat",
    places: [
      "Select a City/Municipality",
      "Bagumbayan",
      "Columbio",
      "Esperanza",
      "Isulan",
      "Kalamansig",
      "Lambayong (Mariano Marcos)",
      "Lebak",
      "Lutayan",
      "Palimbang",
      "President Quirino",
      "Senator Ninoy Aquino (Senator Ninoy Aquino)",
      "Tacurong",
    ],
  },
  {
    name: "Sulu",
    places: [
      "Select a City/Municipality",
      "Hadji Panglima Tahil (Marunggas)",
      "Indanan",
      "Jolo",
      "Kalingalan Caluang",
      "Lugus",
      "Luuk",
      "Maimbung",
      "Old Panamao",
      "Omar",
      "Pandami",
      "Panglima Estino (New Panamao)",
      "Pangutaran",
      "Parang",
      "Pata",
      "Patikul",
      "Siasi",
      "Talipao",
      "Tapul",
      "Tongkil (Banguingui)",
    ],
  },
  {
    name: "Surigao del Norte",
    places: [
      "Select a City/Municipality",
      "Alegria",
      "Bacuag",
      "Burgos",
      "Claver",
      "Dapa",
      "Del Carmen",
      "General Luna",
      "Gigaquit",
      "Mainit",
      "Malimono",
      "Pilar",
      "Placer",
      "San Benito",
      "San Francisco (Anao-Aon)",
      "San Isidro",
      "Santa Monica (Sapao)",
      "Sison",
      "Socorro",
      "Surigao",
      "Tagana-an",
      "Tubod",
    ],
  },
  {
    name: "Surigao del Sur",
    places: [
      "Select a City/Municipality",
      "Barobo",
      "Bayabas",
      "Bislig",
      "Cagwait",
      "Cantilan",
      "Carmen",
      "Carrascal",
      "Cortes",
      "Hinatuan",
      "Lanuza",
      "Lianga",
      "Lingig",
      "Madrid",
      "Marihatag",
      "San Agustin",
      "San Miguel",
      "Tagbina",
      "Tago",
      "Tandag",
    ],
  },
  {
    name: "Tawi-Tawi",
    places: [
      "Select a City/Municipality",
      "Bongao",
      "Languyan",
      "Mapun (Cagayan de Tawi-Tawi)",
      "Panglima Sugala (Balimbing)",
      "Sapa-Sapa",
      "Sibutu",
      "Simunul",
      "Sitangkai",
      "South Ubian",
      "Tandubas",
      "Turtle Islands",
    ],
  },
  {
    name: "Zamboanga del Norte",
    places: [
      "Select a City/Municipality",
      "Bacungan (Leon T. Postigo)",
      "Baliguian",
      "Dapitan",
      "Dipolog",
      "Godod",
      "Gutalac",
      "Jose Dalman (Ponot)",
      "Kalawit",
      "Katipunan",
      "Labason",
      "La Libertad",
      "Liloy",
      "Manukan",
      "Mutia",
      "Piñan (New Piñan)",
      "Polanco",
      "President Manuel A. Roxas",
      "Rizal",
      "Salug",
      "Sergio Osmeña Sr.",
      "Siayan",
      "Sibuco",
      "Sibutad",
      "Sindangan",
      "Siocon",
      "Sirawai",
      "Tampilisan",
      "",
    ],
  },
  {
    name: "Zamboanga del Sur",
    places: [
      "Select a City/Municipality",
      "Aurora",
      "Bayog",
      "Dimataling",
      "Dinas",
      "Dumalinao",
      "Dumingag",
      "Guipos",
      "Josefina",
      "Kumalarang",
      "Labangan",
      "Lakewood",
      "Lapuyan",
      "Mahayag",
      "Margosatubig",
      "Midsalip",
      "Molave",
      "Pagadian",
      "Pitogo",
      "Ramon Magsaysay (Liargo)",
      "San Miguel",
      "San Pablo",
      "Sominot (Don Mariano Marcos)",
      "Tabina",
      "Tambulig",
      "Tigbao",
      "Tukuran",
      "Vincenzo A. Sagun",
      "Zamboanga",
    ],
  },
  {
    name: "Zamboanga Sibugay",
    places: [
      "Select a City/Municipality",
      "Alicia",
      "Buug",
      "Diplahan",
      "Imelda",
      "Ipil",
      "Kabasalan",
      "Mabuhay",
      "Malangas",
      "Naga",
      "Olutanga",
      "Payao",
      "Roseller Lim",
      "Siay",
      "Talusan",
      "Titay",
      "Tungawan",
    ],
  },
  {
    name: "Camiguin",
    places: ["Catarman", "Guinsiliban", "Mahinog", "Mambajao", "Sagay"],
  },
  { name: "City of Isabela", places: ["Isabela"] },
];

export default provinceAndMunicipality;
